import XCTest
@testable import Sidekey

/// Tests for the launch-time purge of clipboard history.
///
/// **Privacy contract**: clipboard rows MUST NOT survive a Sidekey
/// restart. The contents can include passwords, API tokens or other
/// secrets the user copied into another app — none of which we want to
/// persist on disk between sessions. Agent + drop history are exempt
/// because their content is generated by Sidekey itself.
///
/// The purge wipes the `clipboard_entries` table AND every sidecar file
/// in the assets directory. It is called by `AppDelegate` immediately
/// before the clipboard watcher starts so the strip never reads stale
/// pre-restart rows.
final class ClipboardHistoryLaunchPurgeTests: XCTestCase {
    func testWipesClipboardRowsButLeavesAgentAndDropIntact() throws {
        let dbPath = makeTempDBPath()
        let assetsDir = makeTempAssetsDir()
        defer {
            try? FileManager.default.removeItem(atPath: dbPath)
            try? FileManager.default.removeItem(at: assetsDir)
        }

        // Pre-populate the store with one row in each category to mimic
        // a pre-existing on-disk state from a prior session.
        do {
            let store = try SQLiteHistoryStore(path: dbPath)
            _ = try store.insertAgentEntry(
                createdAt: Date(timeIntervalSince1970: 100),
                queryText: "agent survives",
                queryMode: .text,
                responseMarkdown: "yes",
                toolNames: []
            )
            _ = try store.insertDropEntry(
                createdAt: Date(timeIntervalSince1970: 101),
                rawTranscript: "drop survives",
                formattedText: "Drop survives.",
                targetApp: "Mail"
            )
            _ = try store.insertClipboardTextEntry(
                createdAt: Date(timeIntervalSince1970: 102),
                text: "clipboard does not survive"
            )
        }

        // Reopen + purge — the operation the app performs at launch.
        let reopened = try SQLiteHistoryStore(path: dbPath)
        ClipboardHistoryLaunchPurge.run(store: reopened, assetsDirectory: assetsDir)

        let agent = try reopened.latestAgentEntries(limit: 10)
        XCTAssertEqual(agent.count, 1, "agent history must persist across restart")
        XCTAssertEqual(agent.first?.queryText, "agent survives")

        let drops = try reopened.latestDropEntries(limit: 10)
        XCTAssertEqual(drops.count, 1, "drop history must persist across restart")
        XCTAssertEqual(drops.first?.rawTranscript, "drop survives")

        let clipboard = try reopened.latestClipboardEntries(limit: 10)
        XCTAssertEqual(clipboard.count, 0, "clipboard history must NOT persist across restart")
    }

    func testWipesAssetsDirectoryContents() throws {
        let dbPath = makeTempDBPath()
        let assetsDir = makeTempAssetsDir()
        defer {
            try? FileManager.default.removeItem(atPath: dbPath)
            try? FileManager.default.removeItem(at: assetsDir)
        }

        // Drop a clipboard image entry so a real sidecar file exists in
        // the assets dir prior to the purge.
        let uuid = UUID(uuidString: "AAAAAAAA-1111-1111-1111-111111111111")!
        do {
            let store = try SQLiteHistoryStore(path: dbPath)
            _ = try store.insertClipboardImageEntry(
                createdAt: Date(timeIntervalSince1970: 50),
                uuid: uuid,
                imageData: Data(repeating: 0xAB, count: 32),
                imageExtension: "png",
                thumbnailData: Data(repeating: 0xCD, count: 8),
                assetsDirectory: assetsDir
            )
        }
        let sidecar = assetsDir.appendingPathComponent("\(uuid.uuidString).png")
        XCTAssertTrue(
            FileManager.default.fileExists(atPath: sidecar.path),
            "pre-purge sanity: sidecar must exist"
        )

        let reopened = try SQLiteHistoryStore(path: dbPath)
        ClipboardHistoryLaunchPurge.run(store: reopened, assetsDirectory: assetsDir)

        XCTAssertFalse(
            FileManager.default.fileExists(atPath: sidecar.path),
            "clipboard sidecar must be removed at launch"
        )
        let clipboard = try reopened.latestClipboardEntries(limit: 10)
        XCTAssertEqual(clipboard.count, 0)
    }

    func testIsIdempotentOnEmptyStore() throws {
        let dbPath = makeTempDBPath()
        let assetsDir = makeTempAssetsDir()
        defer {
            try? FileManager.default.removeItem(atPath: dbPath)
            try? FileManager.default.removeItem(at: assetsDir)
        }

        let store = try SQLiteHistoryStore(path: dbPath)
        // First run on an empty store should be a no-op.
        ClipboardHistoryLaunchPurge.run(store: store, assetsDirectory: assetsDir)
        // Second run still a no-op.
        ClipboardHistoryLaunchPurge.run(store: store, assetsDirectory: assetsDir)

        XCTAssertEqual(try store.latestClipboardEntries(limit: 10).count, 0)
        XCTAssertEqual(try store.latestAgentEntries(limit: 10).count, 0)
        XCTAssertEqual(try store.latestDropEntries(limit: 10).count, 0)
    }

    func testToleratesMissingAssetsDirectory() throws {
        let dbPath = makeTempDBPath()
        let assetsDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("sidekey-clipboard-purge-missing-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(atPath: dbPath) }

        XCTAssertFalse(
            FileManager.default.fileExists(atPath: assetsDir.path),
            "assets dir should not exist for this test"
        )

        let store = try SQLiteHistoryStore(path: dbPath)
        // The purge must not throw when the assets dir is missing
        // entirely — fresh installs hit this path before the first
        // clipboard image insert creates the directory.
        ClipboardHistoryLaunchPurge.run(store: store, assetsDirectory: assetsDir)
    }

    // MARK: - Helpers

    private func makeTempDBPath() -> String {
        FileManager.default.temporaryDirectory
            .appendingPathComponent("sidekey-clipboard-purge-\(UUID().uuidString).sqlite")
            .path
    }

    private func makeTempAssetsDir() -> URL {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("sidekey-clipboard-purge-assets-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }
}
