import Foundation
import os.log

/// Wipes clipboard history at app launch.
///
/// **Privacy contract**: clipboard rows MUST NOT survive a Sidekey
/// restart. The contents of a copy event can include passwords, API
/// tokens, or other secrets the user grabbed in another app — none of
/// which we want to persist on disk between sessions. Agent + drop
/// history are exempt because their content is generated by Sidekey
/// itself with user awareness; clipboard is "everything the user ever
/// copied", which is too broad to retain.
///
/// `AppDelegate` calls `run(store:assetsDirectory:)` once during
/// `applicationDidFinishLaunching`, immediately after the SQLite store
/// is opened and BEFORE `ClipboardWatcher.start()` so the strip never
/// reads stale pre-restart rows even momentarily.
///
/// Errors are swallowed — purge is best-effort. A failure here MUST NOT
/// break the user-visible app flow; at worst a single residual row
/// survives until the next launch.
enum ClipboardHistoryLaunchPurge {
    private static let log = OSLog(
        subsystem: "com.rootwise.sidekey",
        category: "clipboard.purge"
    )

    /// Drops every row from `clipboard_entries` and removes every file
    /// under `assetsDirectory`. Safe to call multiple times and tolerant
    /// of a missing assets directory (fresh installs).
    static func run(store: SQLiteHistoryStore, assetsDirectory: URL) {
        do {
            try store.wipeAllClipboardEntries(assetsDirectory: assetsDirectory)
            os_log(
                "clipboard_history_launch_purge ok",
                log: Self.log,
                type: .info
            )
        } catch {
            os_log(
                "clipboard_history_launch_purge_failed error=%{public}@",
                log: Self.log,
                type: .error,
                String(describing: type(of: error))
            )
        }
    }
}
